/*
 * ============================================================
 * MODULE 10
 * Automated R Markdown Final Report
 *
 * Generates:
 *   - pipeline_report.docx
 *   - pipeline_report.html
 *   - figures/
 *   - tables/
 *
 * Uses the QIIME2 results generated by previous modules.
 * ============================================================
 */

process R_REPORT {

    tag "Generate final R Markdown report"

    publishDir "${params.outdir}/r_report", mode: 'copy'

    container '/SCRATCH/interns/keerti/Pipeline/16s_Amplicon/R.sif'

    input:
    path results_dir
    path metadata

    path done_import
    path done_denoise
    path done_phylogeny
    path done_taxonomy
    path done_core_diversity
    path done_alpha_group
    path done_rarefaction
    path done_differential

    output:
    path "report/pipeline_report.docx", emit: report_docx
    path "report/pipeline_report.html", emit: report_html
    path "report/figures", emit: figures
    path "report/tables", emit: tables

    script:

    def group_col = params.group_column ?: 'Health_State'

    """
    set -e

    echo "=================================================="
    echo "MODULE 10: FINAL R REPORT"
    echo "=================================================="

    echo
    echo "Working directory:"
    pwd

    echo
    echo "R version:"
    Rscript --version

    echo
    echo "Creating report directories..."

    mkdir -p report
    mkdir -p report/results
    mkdir -p report/figures
    mkdir -p report/tables

    echo
    echo "=================================================="
    echo "Copying report templates"
    echo "=================================================="

    cp ${projectDir}/templates/Report.Rmd \
       report/Report.Rmd

    cp ${projectDir}/templates/plots.R \
       report/plots.R

    echo "Report.Rmd copied"
    echo "plots.R copied"

    echo
    echo "=================================================="
    echo "Copying QIIME2 results"
    echo "=================================================="

    cp -a ${results_dir}/. \
       report/results/

    echo "QIIME2 results copied"

    echo
    echo "Removing old QZV index..."
    
    rm -rf report/results/qzv_index

    echo
    echo "=================================================="
    echo "Copying metadata"
    echo "=================================================="

    cp ${metadata} \
       report/metadata.tsv

    echo "Metadata copied"

    cd report

    export GROUP_COLUMN="${group_col}"

    echo
    echo "Group column:"
    echo "\${GROUP_COLUMN}"

    echo
    echo "=================================================="
    echo "Checking required R packages"
    echo "=================================================="

    Rscript - <<'RSCRIPT'

required <- c(
    "ggplot2",
    "dplyr",
    "tidyr",
    "readr",
    "stringr",
    "tibble",
    "knitr",
    "rmarkdown",
    "kableExtra"
)

missing <- required[
    !vapply(
        required,
        requireNamespace,
        logical(1),
        quietly = TRUE
    )
]

if (length(missing) > 0) {

    stop(
        paste(
            "Missing R packages:",
            paste(missing, collapse = ", ")
        )
    )

}

cat("All required R packages are installed.\\n")

RSCRIPT

    echo
    echo "=================================================="
    echo "Checking Pandoc"
    echo "=================================================="

    Rscript -e 'cat("Pandoc version:", as.character(rmarkdown::pandoc_version()), "\\n")'

    echo
    echo "=================================================="
    echo "Running plots.R"
    echo "=================================================="

    Rscript plots.R \
        results \
        . \
        metadata.tsv \
        "\${GROUP_COLUMN}"

    echo
    echo "=================================================="
    echo "Generating DOCX report"
    echo "=================================================="

    Rscript - <<'RSCRIPT'

rmarkdown::render(
    input = "Report.Rmd",
    output_format = "word_document",
    output_file = "pipeline_report.docx",
    params = list(
        group_column = Sys.getenv(
            "GROUP_COLUMN",
            unset = "Health_State"
        )
    ),
    envir = new.env()
)

RSCRIPT

    echo
    echo "=================================================="
    echo "Generating HTML report"
    echo "=================================================="

    Rscript - <<'RSCRIPT'

rmarkdown::render(
    input = "Report.Rmd",
    output_format = "html_document",
    output_file = "pipeline_report.html",
    params = list(
        group_column = Sys.getenv(
            "GROUP_COLUMN",
            unset = "Health_State"
        )
    ),
    envir = new.env()
)

RSCRIPT

    echo
    echo "=================================================="
    echo "FINAL REPORT FILES"
    echo "=================================================="

    echo
    echo "DOCX:"
    ls -lh pipeline_report.docx

    echo
    echo "HTML:"
    ls -lh pipeline_report.html

    echo
    echo "Figures:"
    find figures -type f -print | sort || true

    echo
    echo "Tables:"
    find tables -type f -print | sort || true

    echo
    echo "=================================================="
    echo "MODULE 10 COMPLETED"
    echo "=================================================="
    """
}
